from discoveryworld.objects.Object import Object
from discoveryworld.objects.Archaeology import *
from discoveryworld.objects.Chemistry import *
from discoveryworld.objects.Farming import *
from discoveryworld.objects.Furnitures import *
from discoveryworld.objects.ScienceTools import *
from discoveryworld.objects.Terrain import *
from discoveryworld.objects.Tools import *
from discoveryworld.objects.ReactorLab import *
